-- Sawubona datahub: Postgres baseline, replacing upstream's MySQL/PlanetScale
-- migrations 0000-0004 (see devops/terraform/servers/discovery-one/sql/).
-- Generated by drizzle-kit from src/db/schema.ts, plus the hand-written
-- updated_at trigger at the end (drizzle cannot express triggers).
CREATE TABLE IF NOT EXISTS "object_item" (
	"id" bigserial PRIMARY KEY NOT NULL,
	"object_id" varchar(32) NOT NULL,
	"object_iri" text NOT NULL,
	"object_list_id" bigint NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(50) NOT NULL,
	CONSTRAINT "object_item_object_id_object_list_id_unique" UNIQUE("object_id","object_list_id")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "object_list" (
	"id" bigserial PRIMARY KEY NOT NULL,
	"name" varchar(256) NOT NULL,
	"description" text,
	"community_id" varchar(50),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(256) NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "object_item_object_id" ON "object_item" ("object_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "object_item_object_list_id" ON "object_item" ("object_list_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "object_list_community_id" ON "object_list" ("community_id");--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "object_item" ADD CONSTRAINT "object_item_object_list_id_object_list_id_fk" FOREIGN KEY ("object_list_id") REFERENCES "object_list"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;

--> statement-breakpoint
CREATE OR REPLACE FUNCTION set_updated_at() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$;
--> statement-breakpoint
DO $$ BEGIN
 CREATE TRIGGER object_list_set_updated_at
  BEFORE UPDATE ON "object_list"
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
